export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const SET_BRAND_FILTER = 'SET_BRAND_FILTER';
export const SORT_PRODUCTS = 'SORT_PRODUCTS';
export const GET_ALL_PRODUCTS_SUCCESS = 'GET_ALL_PRODUCTS_SUCCESS';
export const GET_ALL_PRODUCTS_FAIL = 'GET_ALL_PRODUCTS_FAIL';
